@ToDoList.Api_HostAddress = http://localhost:5199

GET {{ToDoList.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

# Testar listas do usuário
GET {{ToDoList.Api_HostAddress}}/api/Lista/usuario/4
Accept: application/json

###
